<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.2.0</Version>
    <Authors>iyulab</Authors>
    <Description>Command and result models for CodeBeaker's multi-runtime code execution platform.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/iyulab/code-beaker</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" Version="4.3.3" />
  </ItemGroup>

</Project>
