version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/CodeBeaker.API/Dockerfile
    container_name: codebeaker-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Queue__Path=/data/queue
      - Storage__Path=/data/storage
    volumes:
      - codebeaker-data:/data
    networks:
      - codebeaker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: src/CodeBeaker.Worker/Dockerfile
    container_name: codebeaker-worker
    environment:
      - Queue__Path=/data/queue
      - Storage__Path=/data/storage
      - Worker__MaxConcurrency=10
      - Worker__PollIntervalSeconds=1
      - Worker__MaxRetries=3
    volumes:
      - codebeaker-data:/data
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker
    networks:
      - codebeaker-network
    depends_on:
      - api

volumes:
  codebeaker-data:
    driver: local

networks:
  codebeaker-network:
    driver: bridge
