apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebeaker-api
  namespace: codebeaker
  labels:
    app.kubernetes.io/name: codebeaker
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: codebeaker-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: codebeaker
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: codebeaker
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: codebeaker-platform
    spec:
      containers:
      - name: api
        image: codebeaker/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5039
          protocol: TCP
        env:
        - name: QUEUE_BASE_DIR
          value: "/data/queue"
        - name: STORAGE_BASE_DIR
          value: "/data/storage"
        envFrom:
        - configMapRef:
            name: codebeaker-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: codebeaker-data
