apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codebeaker

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"
