apiVersion: v1
kind: Service
metadata:
  name: codebeaker-api
  namespace: codebeaker
  labels:
    app.kubernetes.io/name: codebeaker
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: codebeaker
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: codebeaker-api-loadbalancer
  namespace: codebeaker
  labels:
    app.kubernetes.io/name: codebeaker
    app.kubernetes.io/component: api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: codebeaker
    app.kubernetes.io/component: api
