name: CI - Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test Core
      run: |
        dotnet test tests/CodeBeaker.Core.Tests/ \
          --no-build \
          --configuration Release \
          --logger "console;verbosity=normal"

    - name: Test Runtimes
      run: |
        dotnet test tests/CodeBeaker.Runtimes.Tests/ \
          --no-build \
          --configuration Release \
          --logger "console;verbosity=normal"

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Format Check
      run: dotnet format --verify-no-changes --no-restore
